# Generated by Django 5.0.7 on 2024-08-23 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grand_v2_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
