# Generated by Django 5.0.7 on 2024-09-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grand_v2_app', '0002_delete_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('image', 'Cover'), ('image', 'Poster'), ('video', 'Video'), ('image', 'Still')], max_length=255),
        ),
    ]
